### ISSUE TITLE
REQ: Stereo version but with single SC input

### ISSUE THREAD

**Issue by talondnb** [polykit/kosmo-sidechain#1]
Hi, would you happen to know how to create a stereo version of this but without the additional sidechain and to retain the existing single pole pots? Perhaps doubling up the vactrol section would be required, but how would the release control be tapped in to control both channels?

Thanks in advance.

**Comment by polykit** [comment]
@talondnb I think you need to duplicate everything onwards the op-amp U1C (including it). The op-amp is only capable of driving one vactrol. For the mix pot you can use a stereo one to control both circuits at the same time.

**Comment by talondnb** [comment]
Thank you, I’ll try and give this a shot!
